# Generated by Django 5.0.7 on 2026-04-30 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="folder",
                        max_length=50,
                        verbose_name="icône",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("slug", models.SlugField(max_length=120, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="tasks.category",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "sous-catégorie",
                "verbose_name_plural": "sous-catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "reward",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="rémunération"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publiée"),
                            ("accepted", "Acceptée"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminée"),
                            ("validated", "Validée"),
                            ("rejected", "Refusée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "has_route",
                    models.BooleanField(default=False, verbose_name="avec trajet"),
                ),
                (
                    "departure_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="lat départ",
                    ),
                ),
                (
                    "departure_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="lng départ",
                    ),
                ),
                (
                    "arrival_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="lat arrivée"
                    ),
                ),
                (
                    "arrival_lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="lng arrivée"
                    ),
                ),
                (
                    "departure_address",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="adresse de départ",
                    ),
                ),
                (
                    "arrival_address",
                    models.CharField(max_length=300, verbose_name="adresse d'arrivée"),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="photos"),
                ),
                (
                    "files",
                    models.JSONField(blank=True, default=list, verbose_name="fichiers"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="publiée le"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date limite"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifiée le"),
                ),
                (
                    "assigned_tasker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tasker assigné",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="tasks.category",
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="client",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="tasks.subcategory",
                        verbose_name="sous-catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "tâche",
                "verbose_name_plural": "tâches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="description de la preuve"),
                ),
                (
                    "photos",
                    models.JSONField(blank=True, default=list, verbose_name="photos"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="soumise le"),
                ),
                (
                    "client_review",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("revision", "Modification demandée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="révision client",
                    ),
                ),
                (
                    "revision_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="notes de révision"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="révisée le"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof",
                        to="tasks.task",
                        verbose_name="tâche",
                    ),
                ),
                (
                    "tasker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="tasker",
                    ),
                ),
            ],
            options={
                "verbose_name": "preuve",
                "verbose_name_plural": "preuves",
            },
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"), name="unique_category_subcategory_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "-published_at"], name="tasks_task_status_3723fc_idx"
            ),
        ),
    ]
