# Generated by Django 5.0.7 on 2026-05-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_arrival_lat_alter_task_arrival_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.subcategory', verbose_name='sous-catégorie'),
        ),
    ]
