# Generated by Django 5.0.7 on 2026-05-01 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='clôturée le'),
        ),
        migrations.AlterField(
            model_name='task',
            name='arrival_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='lat arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='arrival_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='lng arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('accepted', 'Acceptée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('awaiting_confirmation', 'En attente de confirmation'), ('validated', 'Validée'), ('litige', 'Litige'), ('resolved', 'Résolue'), ('evaluated', 'Évaluée'), ('closed', 'Clôturée'), ('cancelled', 'Annulée'), ('rejected', 'Refusée')], default='draft', max_length=30, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='TaskApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='message du tasker')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='postulé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tasks.task', verbose_name='tâche')),
                ('tasker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_applications', to=settings.AUTH_USER_MODEL, verbose_name='tasker')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='taskapplication',
            constraint=models.UniqueConstraint(fields=('task', 'tasker'), name='unique_task_tasker_application'),
        ),
    ]
