# Generated by Django 5.0.7 on 2026-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_closed_at_alter_task_arrival_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arrival_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='lat arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='arrival_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='lng arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='departure_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='lat départ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='departure_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='lng départ'),
        ),
    ]
