# Generated by Django 5.0.7 on 2026-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_arrival_lat_alter_task_arrival_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arrival_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='lat arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='arrival_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='lng arrivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='departure_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='lat départ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='departure_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='lng départ'),
        ),
    ]
