# Generated by Django 5.0.7 on 2026-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_arrival_lat_alter_task_arrival_lng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="proof_required",
            field=models.BooleanField(default=False, verbose_name="preuve requise"),
        ),
    ]
