# Generated by Django 5.0.7 on 2026-05-29 21:05

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_proof_required_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=apps.tasks.models.Task._default_deadline, help_text='Délai par défaut : 7 jours', null=True, verbose_name='date limite'),
        ),
    ]
