# Generated by Django 6.0.5 on 2026-06-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'tâche', 'verbose_name_plural': 'tâches'},
        ),
        migrations.AlterField(
            model_name='taskapplication',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tasks.task', verbose_name='tâche'),
        ),
        migrations.AlterField(
            model_name='taskproof',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='tasks.task', verbose_name='tâche'),
        ),
    ]
