# Generated by Django 6.0.5 on 2026-06-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_options_alter_taskapplication_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='arrival_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name="adresse d'arrivée"),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='titre'),
        ),
    ]
