# Generated by Django 5.0.7 on 2026-04-30 19:02

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="nom complet"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="téléphone"
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="téléphone vérifié"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="photo de profil",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("tasker", "Tasker"),
                            ("both", "Client & Tasker"),
                        ],
                        default="client",
                        max_length=10,
                        verbose_name="rôle",
                    ),
                ),
                (
                    "active_role",
                    models.CharField(
                        choices=[("client", "Client"), ("tasker", "Tasker")],
                        default="client",
                        max_length=10,
                        verbose_name="rôle actif",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="vérifié"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
            managers=[
                ("objects", apps.accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="biographie"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ville"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "tasker_rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="note tasker moyenne",
                    ),
                ),
                (
                    "tasker_rating_count",
                    models.IntegerField(default=0, verbose_name="nombre avis tasker"),
                ),
                (
                    "client_rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="note client moyenne",
                    ),
                ),
                (
                    "client_rating_count",
                    models.IntegerField(default=0, verbose_name="nombre avis client"),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(default=0, verbose_name="tâches réalisées"),
                ),
                (
                    "tasks_published",
                    models.IntegerField(default=0, verbose_name="tâches publiées"),
                ),
                (
                    "tasks_cancelled",
                    models.IntegerField(default=0, verbose_name="tâches annulées"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
            },
        ),
        migrations.CreateModel(
            name="VerificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("phone", "Téléphone"), ("face_id", "Face ID")],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=6, null=True, verbose_name="code"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expire le")),
                ("is_used", models.BooleanField(default=False, verbose_name="utilisé")),
                (
                    "face_photo_initial",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="face-id/",
                        verbose_name="photo initiale",
                    ),
                ),
                (
                    "face_photo_left",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="face-id/",
                        verbose_name="photo gauche",
                    ),
                ),
                (
                    "face_photo_right",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="face-id/",
                        verbose_name="photo droite",
                    ),
                ),
                (
                    "face_photo_blink",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="face-id/",
                        verbose_name="photo clignement",
                    ),
                ),
                (
                    "face_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="statut face ID",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, null=True, verbose_name="notes admin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "vérification",
                "verbose_name_plural": "vérifications",
            },
        ),
        migrations.AddConstraint(
            model_name="verificationrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "type"), name="unique_user_verification_type"
            ),
        ),
    ]
