# Generated by Django 5.0.7 on 2026-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="active_role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("tasker", "Tasker"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=10,
                verbose_name="rôle actif",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("tasker", "Tasker"),
                    ("both", "Client & Tasker"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=10,
                verbose_name="rôle",
            ),
        ),
    ]
