# Generated by Django 5.0.7 on 2026-05-01 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_active_role_alter_customuser_role'),
        ('messaging', '0002_conversation_is_closed_conversation_is_reported_and_more'),
        ('tasks', '0004_task_closed_at_alter_task_arrival_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='niveau'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0, verbose_name="points d'expérience"),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task_published', 'Nouvelle tâche publiée'), ('task_accepted', 'Tâche acceptée'), ('task_completed', 'Tâche terminée'), ('message_received', 'Nouveau message'), ('review_received', 'Nouvel avis'), ('system', 'Système')], max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('is_opened', models.BooleanField(default=False, verbose_name='ouverte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='ouverte le')),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation', verbose_name='conversation liée')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='tâche liée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
