# Generated by Django 5.0.7 on 2026-05-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_level_userprofile_xp_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_published', 'Nouvelle tâche publiée'), ('new_application', 'Nouvelle candidature'), ('task_accepted', 'Tâche acceptée'), ('task_completed', 'Tâche terminée'), ('message_received', 'Nouveau message'), ('review_received', 'Nouvel avis'), ('system', 'Système')], max_length=30, verbose_name='type'),
        ),
    ]
