# Generated by Django 5.0.7 on 2026-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_new_application_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email vérifié'),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='type',
            field=models.CharField(choices=[('phone', 'Téléphone'), ('email', 'Email'), ('face_id', 'Face ID')], max_length=10, verbose_name='type'),
        ),
    ]
