# Generated by Django 5.0.7 on 2026-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_seen",
            field=models.BooleanField(default=False, verbose_name="guide vu"),
        ),
    ]
