# Generated by Django 5.0.7 on 2026-05-25 22:44

from django.db import migrations


def set_onboarding_seen_for_existing(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(onboarding_seen=False).update(onboarding_seen=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_onboarding_seen"),
    ]

    operations = [
        migrations.RunPython(set_onboarding_seen_for_existing, migrations.RunPython.noop),
    ]
