# Generated by Django 5.0.7 on 2026-05-26 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_seed_onboarding_seen"),
        ("reputation", "0003_alter_review_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reputation.review",
                verbose_name="avis lié",
            ),
        ),
    ]
