# Generated by Django 5.0.7 on 2026-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_notification_related_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(default=0, verbose_name="série actuelle"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_streak_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="dernière activité"
            ),
        ),
    ]
