# Generated by Django 6.0.5 on 2026-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_streak_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="UID Firebase",
            ),
        ),
    ]
