# Generated by Django 6.0.5 on 2026-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_streak_fields'),
        ('tasks', '0008_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_tasks',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='tasks.task'),
        ),
    ]
