# Generated by Django 6.0.5 on 2026-06-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_merge_0010_branches"),
        ("tasks", "0009_alter_task_options_alter_taskapplication_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.task",
                verbose_name="task liée",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_published", "Nouvelle task publiée"),
                    ("new_application", "Nouvelle candidature"),
                    ("task_accepted", "Task acceptée"),
                    ("task_completed", "Task terminée"),
                    ("message_received", "Nouveau message"),
                    ("review_received", "Nouvel avis"),
                    ("system", "Système"),
                ],
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tasks_cancelled",
            field=models.IntegerField(default=0, verbose_name="tasks annulées"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tasks_completed",
            field=models.IntegerField(default=0, verbose_name="tasks réalisées"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tasks_published",
            field=models.IntegerField(default=0, verbose_name="tasks publiées"),
        ),
    ]
