# Generated by Django 6.0.5 on 2026-06-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notification_related_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='rappel profil envoyé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='welcome_modal_shown',
            field=models.BooleanField(default=False, verbose_name='modal bienvenue vue'),
        ),
    ]
