# Generated by Django 6.0.5 on 2026-06-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_welcome_modal_fields'),
        ('tasks', '0011_alter_task_options_alter_taskapplication_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('icon', models.CharField(blank=True, default='ti-tools', max_length=50, verbose_name='icône')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_avatar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='service_radius',
            field=models.IntegerField(blank=True, null=True, verbose_name="rayon d'action (km)"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='tâche liée'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_published', 'Nouvelle tâche publiée'), ('new_application', 'Nouvelle candidature'), ('task_accepted', 'Tâche acceptée'), ('application_rejected', 'Candidature non retenue'), ('task_completed', 'Tâche terminée'), ('message_received', 'Nouveau message'), ('review_received', 'Nouvel avis'), ('system', 'Système')], max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_cancelled',
            field=models.IntegerField(default=0, verbose_name='tâches annulées'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_completed',
            field=models.IntegerField(default=0, verbose_name='tâches réalisées'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tasks_published',
            field=models.IntegerField(default=0, verbose_name='tâches publiées'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill', verbose_name='compétences'),
        ),
    ]
