# Generated by Django 6.0.5 on 2026-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_skill_userprofile__xp_awarded_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('menage', 'Ménage'), ('bricolage', 'Bricolage & Réparation'), ('jardinage', 'Jardinage'), ('livraison', 'Livraison'), ('courses', 'Courses & Shopping'), ('tech', 'Tech & Digital'), ('enseignement', 'Enseignement & Cours'), ('soins', 'Soins & Bien-être'), ('transport', 'Transport'), ('evenementiel', 'Événementiel'), ('garde', 'Garde & Animaux'), ('autre', 'Autre')], default='', max_length=30, verbose_name='catégorie'),
        ),
    ]
