# Generated by Django 6.0.5 on 2026-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_deletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_last_daily_xp_date',
            field=models.DateField(blank=True, null=True, verbose_name='dernier XP quotidien'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_first_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_xp_awarded_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level_title',
            field=models.CharField(default='Apprenti', max_length=50, verbose_name='titre de niveau'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='série la plus longue (semaines)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='série actuelle (semaines)'),
        ),
    ]
