# Generated by Django 6.0.5 on 2026-06-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_gamification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='_last_daily_xp_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longest_streak',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='série actuelle'),
        ),
    ]
