# Generated by Django 5.0.7 on 2026-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='clôturée'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_reported',
            field=models.BooleanField(default=False, verbose_name='signalée'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='report_reason',
            field=models.TextField(blank=True, null=True, verbose_name='raison du signalement'),
        ),
    ]
