# Generated by Django 6.0.5 on 2026-06-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_link_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='fichier'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='nom du fichier'),
        ),
    ]
