# Generated by Django 6.0.5 on 2026-06-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


def merge_duplicate_conversations(apps, schema_editor):
    Conversation = apps.get_model('messaging', 'Conversation')
    Message = apps.get_model('messaging', 'Message')

    pairs = (
        Conversation.objects.values('client_id', 'tasker_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for pair in pairs:
        convs = list(
            Conversation.objects.filter(
                client_id=pair['client_id'],
                tasker_id=pair['tasker_id'],
            ).annotate(msg_count=Count('messages')).order_by('-msg_count', '-last_activity_at')
        )

        if len(convs) < 2:
            continue

        survivor = convs[0]
        victims = convs[1:]

        victim_ids = [v.id for v in victims]

        Message.objects.filter(conversation_id__in=victim_ids).update(
            conversation_id=survivor.id,
        )

        max_activity = Conversation.objects.filter(id__in=victim_ids).aggregate(
            m=Max('last_activity_at')
        )['m']
        if max_activity and (not survivor.last_activity_at or max_activity > survivor.last_activity_at):
            survivor.last_activity_at = max_activity
            survivor.save(update_fields=['last_activity_at'])

        Conversation.objects.filter(id__in=victim_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='message système'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='expéditeur'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='application',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_closed',
        ),
        migrations.RunPython(merge_duplicate_conversations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('client', 'tasker'), name='unique_client_tasker_pair'),
        ),
    ]
