# Generated by Django 5.0.7 on 2026-05-01 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('reported', 'Signalée'), ('hidden', 'Masquée')], default='draft', max_length=20, verbose_name='statut de modération'),
        ),
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.TextField(blank=True, null=True, verbose_name='raison du signalement'),
        ),
        migrations.AddField(
            model_name='review',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='signalé par'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note'),
        ),
    ]
