# Generated by Django 5.0.7 on 2026-05-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0002_review_moderation_status_review_report_reason_and_more"),
        ("tasks", "0006_alter_task_arrival_lat_alter_task_arrival_lng_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tasks.task",
                verbose_name="tâche",
            ),
        ),
    ]
