# Generated by Django 6.0.5 on 2026-06-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reputation", "0003_alter_review_task"),
        ("tasks", "0009_alter_task_options_alter_taskapplication_task_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="tasks.task",
                verbose_name="task",
            ),
        ),
    ]
