# Generated by Django 5.0.7 on 2026-04-30 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="slug"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "icon",
                    models.CharField(
                        default="badge", max_length=50, verbose_name="icône"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4F46E5", max_length=7, verbose_name="couleur"
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("tasks_completed", "Tâches réalisées"),
                            ("avg_rating", "Note moyenne"),
                            ("speed", "Rapidité"),
                            ("no_cancel", "Aucune annulation"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                        verbose_name="type de condition",
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(
                        default=dict,
                        help_text='Ex: {"min_tasks": 10, "min_rating": 4.5}',
                        verbose_name="valeur de condition",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("tasker", "Tasker"),
                            ("client", "Client"),
                            ("both", "Les deux"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="rôle cible",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "badge",
                "verbose_name_plural": "badges",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="obtenu le"),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="badges.badge",
                        verbose_name="badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges_earned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "badge utilisateur",
                "verbose_name_plural": "badges utilisateur",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="unique_user_badge"
            ),
        ),
    ]
